### ISSUE TITLE
[V-PHX-VUL-007] The usage of assert_max_spread assume pool tokens have the same amount of decimals

### ISSUE THREAD

**Issue by gangov** [Phoenix-Protocol-Group/phoenix-contracts#207]
files: *contracts/pool/src/contract.rs*
location: *do_swap, assert_max_spread*

The do_swap function allows the user to specify a belief_price. This value works as an slippage protection for the user’s swap, protecting the user to perform a bad swap. At the beginning of do_swap we can find:

```Rust
let belief_price = belief_price.map(Decimal::percent);
```
_Code snippet from the `do_swap` function. The code transforms `belief_price` to a `Decimal`._

From the above code, we know that `belief_price` is given in units of percents. Hence, a `belief_price` of 100 will be transformed to a Decimal with numerator of `1e18`. Meaning that the expected swap should be 1:1.
Looking at the `assert_max_spread` function, we found:
```Rust
let expected_return = belief_price.map(|price| offer_amount * price);
```
_Code snippet from the `assert_max_spread` function. The code computes the expected_return from the swap operation._

If `belief_price` were to be `1e18` then this will yield: `offer_amount * 1e18 / 1e18`. Which is equal to `offer_amount`.

The above is problematic since the tokens for `offer_amount` and `expected_return` may not have the same decimal precision.

**Impact** Depending on which token has more and less decimal precision, the execution will panic due to the spread being too much, or it will continue at the possibility of the user making a bad swap.

**Recommendation** `belief_price` should take into account the tokens decimal precision.

**Comment by ueco-jb** [comment]
We removed the belief price argument, thus rending this issue no longer valid.
https://github.com/Phoenix-Protocol-Group/phoenix-contracts/pull/280
