### ISSUE TITLE
[V-PHX-VUL-018] Soroban storage limitation discourages staking

### ISSUE THREAD

**Issue by gangov** [Phoenix-Protocol-Group/phoenix-contracts#218]
file: *contracts/stake/src/storage.rs*
location: *BondingInfo*

Similar to the [V-PHX-VUL-008 issue](https://github.com/Phoenix-Protocol-Group/phoenix-contracts/issues/208), the stakes vector in a user’s `BondingInfo` grows with each subsequent bond operation that a user performs. Therefore, each bond operation will become more and more expensive for the user to perform and could eventually exceed the transaction storage limit.

**Impact:** This impacts the usability of the staking contract and discourages users from having many stakes in the contract.

**Recommendation:** Since the `stake_timestamp` of each stake is not checked or used after a stake is created, and the `WithdrawAdjustment` tracks adjustments based on the time the user performs a bond, the `BondingInfo` could solely track a user’s `total_stake` and omit storing all of the user’s individual stake operations.

**Comment by ueco-jb** [comment]
This implementation will be modified, but staking timestamps are important.
