### ISSUE TITLE
[V-PHX-VUL-029] Compilation errors

### ISSUE THREAD

**Issue by gangov** [Phoenix-Protocol-Group/phoenix-contracts#224]
files: *contracts/pool_stable/**
location: *contracts/pool_stable/*

Commit 384c8cf does not compile due to the changes made in `pool_stable`. This can be reproduced by running make test.

**Impact:** There are errors in the code that need to be corrected.

**Recommendation:** Fix the compilation issues and ensure the tests run successfully.

**Comment by ueco-jb** [comment]
Current main branch compiles successfully.
