### ISSUE TITLE
PHOAM-009: Adversaries can sandwich attack every stable pool liquidity provider

### ISSUE THREAD

**Issue by gangov** [Phoenix-Protocol-Group/phoenix-contracts#335]
_Location_
./contracts/pool_stable/src/contract.rs:363

**Description**
Malicious node operators can perform sandwich attacks on each stable pool's provide_liquidity function call for profit, causing users to receive fewer shares than expected. This vulnerability arises because the maximum slippage accepted by the user is not checked when providing liquidity to stable pools.
The provide_liquidity function includes a parameter for users to set slippage.
This function validates that the provided slippage does not exceed the allowed maximum value.

However, there are no checks to ensure that the calculated shares to mint do not deviate from the expected slippage, resulting in the direct minting of the calculated number of shares.
As an example, Curve stable pool's performs this slippage check just before minting the LP shares.

**Recommendation**
Include slippage checks before minting shares. Also, specify a default custom_slippage_bps value when LPs set it as None.

**Comment by ueco-jb** [comment]
The original issue is, we didn't plan to include the slippage there at all. The invariant calculations are making sure that the ratio is being kept. 
I guess you can still frontrun the transaction, we estimated the impact to be a negligable one...
But let's proceced.
