### ISSUE TITLE
Put `ADMIN` under the same key in all of the contract

### ISSUE THREAD

**Issue by ueco-jb** [Phoenix-Protocol-Group/phoenix-contracts#397]
Create a symbol for ADMIN and prepare a migration function that saves the admin under the new key.
In a step 2 when the contracts are migrated, this issue should implement to use the new key instead of the DATA KEY admin.

**Comment by gangov** [comment]
we have a discrepancy in the storage types used to keep the admin value, I think we should settle on just one type.
