### ISSUE TITLE
Stake: Stop distribution

### ISSUE THREAD

**Issue by ueco-jb** [Phoenix-Protocol-Group/phoenix-contracts#87]
Create an entrypoint where either `ADMIN` or manager of given distribution (appointed during creation) can stop it (most effective would be probably reseting the `Curve` to default `Constant(0)`).

**Comment by gangov** [comment]
@ueco-jb I hope it's okay, that I assigned this.

**Comment by ueco-jb** [comment]
After some thinking, it's better to let it run. More issues with handling potentially leftout tokens.
